/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk/index'
import { Route as TokoSlugTokoRouteImport } from './routes/toko/$slugToko'
import { Route as SellerProfilRouteImport } from './routes/seller/profil'
import { Route as SellerLoginRouteImport } from './routes/seller/login'
import { Route as SellerDashboardRouteImport } from './routes/seller/dashboard'
import { Route as ProdukSlugRouteImport } from './routes/produk/$slug'
import { Route as SellerProdukIndexRouteImport } from './routes/seller/produk/index'
import { Route as SellerProdukTambahRouteImport } from './routes/seller/produk/tambah'
import { Route as SellerProdukProdukIdEditRouteImport } from './routes/seller/produk/$produkId/edit'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokoSlugTokoRoute = TokoSlugTokoRouteImport.update({
  id: '/toko/$slugToko',
  path: '/toko/$slugToko',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProfilRoute = SellerProfilRouteImport.update({
  id: '/seller/profil',
  path: '/seller/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerLoginRoute = SellerLoginRouteImport.update({
  id: '/seller/login',
  path: '/seller/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProdukIndexRoute = SellerProdukIndexRouteImport.update({
  id: '/seller/produk/',
  path: '/seller/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProdukTambahRoute = SellerProdukTambahRouteImport.update({
  id: '/seller/produk/tambah',
  path: '/seller/produk/tambah',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProdukProdukIdEditRoute =
  SellerProdukProdukIdEditRouteImport.update({
    id: '/seller/produk/$produkId/edit',
    path: '/seller/produk/$produkId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tentang': typeof TentangRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/profil': typeof SellerProfilRoute
  '/toko/$slugToko': typeof TokoSlugTokoRoute
  '/produk/': typeof ProdukIndexRoute
  '/seller/produk/tambah': typeof SellerProdukTambahRoute
  '/seller/produk/': typeof SellerProdukIndexRoute
  '/seller/produk/$produkId/edit': typeof SellerProdukProdukIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tentang': typeof TentangRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/profil': typeof SellerProfilRoute
  '/toko/$slugToko': typeof TokoSlugTokoRoute
  '/produk': typeof ProdukIndexRoute
  '/seller/produk/tambah': typeof SellerProdukTambahRoute
  '/seller/produk': typeof SellerProdukIndexRoute
  '/seller/produk/$produkId/edit': typeof SellerProdukProdukIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tentang': typeof TentangRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/profil': typeof SellerProfilRoute
  '/toko/$slugToko': typeof TokoSlugTokoRoute
  '/produk/': typeof ProdukIndexRoute
  '/seller/produk/tambah': typeof SellerProdukTambahRoute
  '/seller/produk/': typeof SellerProdukIndexRoute
  '/seller/produk/$produkId/edit': typeof SellerProdukProdukIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tentang'
    | '/produk/$slug'
    | '/seller/dashboard'
    | '/seller/login'
    | '/seller/profil'
    | '/toko/$slugToko'
    | '/produk/'
    | '/seller/produk/tambah'
    | '/seller/produk/'
    | '/seller/produk/$produkId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tentang'
    | '/produk/$slug'
    | '/seller/dashboard'
    | '/seller/login'
    | '/seller/profil'
    | '/toko/$slugToko'
    | '/produk'
    | '/seller/produk/tambah'
    | '/seller/produk'
    | '/seller/produk/$produkId/edit'
  id:
    | '__root__'
    | '/'
    | '/tentang'
    | '/produk/$slug'
    | '/seller/dashboard'
    | '/seller/login'
    | '/seller/profil'
    | '/toko/$slugToko'
    | '/produk/'
    | '/seller/produk/tambah'
    | '/seller/produk/'
    | '/seller/produk/$produkId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TentangRoute: typeof TentangRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerLoginRoute: typeof SellerLoginRoute
  SellerProfilRoute: typeof SellerProfilRoute
  TokoSlugTokoRoute: typeof TokoSlugTokoRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
  SellerProdukTambahRoute: typeof SellerProdukTambahRoute
  SellerProdukIndexRoute: typeof SellerProdukIndexRoute
  SellerProdukProdukIdEditRoute: typeof SellerProdukProdukIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toko/$slugToko': {
      id: '/toko/$slugToko'
      path: '/toko/$slugToko'
      fullPath: '/toko/$slugToko'
      preLoaderRoute: typeof TokoSlugTokoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/profil': {
      id: '/seller/profil'
      path: '/seller/profil'
      fullPath: '/seller/profil'
      preLoaderRoute: typeof SellerProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/login': {
      id: '/seller/login'
      path: '/seller/login'
      fullPath: '/seller/login'
      preLoaderRoute: typeof SellerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/produk/': {
      id: '/seller/produk/'
      path: '/seller/produk'
      fullPath: '/seller/produk/'
      preLoaderRoute: typeof SellerProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/produk/tambah': {
      id: '/seller/produk/tambah'
      path: '/seller/produk/tambah'
      fullPath: '/seller/produk/tambah'
      preLoaderRoute: typeof SellerProdukTambahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/produk/$produkId/edit': {
      id: '/seller/produk/$produkId/edit'
      path: '/seller/produk/$produkId/edit'
      fullPath: '/seller/produk/$produkId/edit'
      preLoaderRoute: typeof SellerProdukProdukIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TentangRoute: TentangRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerLoginRoute: SellerLoginRoute,
  SellerProfilRoute: SellerProfilRoute,
  TokoSlugTokoRoute: TokoSlugTokoRoute,
  ProdukIndexRoute: ProdukIndexRoute,
  SellerProdukTambahRoute: SellerProdukTambahRoute,
  SellerProdukIndexRoute: SellerProdukIndexRoute,
  SellerProdukProdukIdEditRoute: SellerProdukProdukIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
