/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SellerRouteImport } from './routes/_seller'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk/index'
import { Route as TokoSlugTokoRouteImport } from './routes/toko/$slugToko'
import { Route as TokoSellerIdRouteImport } from './routes/toko/$sellerId'
import { Route as SellerRegisterRouteImport } from './routes/seller/register'
import { Route as SellerLoginRouteImport } from './routes/seller/login'
import { Route as ProdukSlugRouteImport } from './routes/produk/$slug'
import { Route as SellerSellerProfilRouteImport } from './routes/_seller/seller/profil'
import { Route as SellerSellerDashboardRouteImport } from './routes/_seller/seller/dashboard'
import { Route as SellerSellerProdukIndexRouteImport } from './routes/_seller/seller/produk/index'
import { Route as SellerSellerProdukTambahRouteImport } from './routes/_seller/seller/produk/tambah'
import { Route as SellerSellerProdukProdukIdEditRouteImport } from './routes/_seller/seller/produk/$produkId/edit'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/_seller',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokoSlugTokoRoute = TokoSlugTokoRouteImport.update({
  id: '/toko/$slugToko',
  path: '/toko/$slugToko',
  getParentRoute: () => rootRouteImport,
} as any)
const TokoSellerIdRoute = TokoSellerIdRouteImport.update({
  id: '/toko/$sellerId',
  path: '/toko/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRegisterRoute = SellerRegisterRouteImport.update({
  id: '/seller/register',
  path: '/seller/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerLoginRoute = SellerLoginRouteImport.update({
  id: '/seller/login',
  path: '/seller/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSellerProfilRoute = SellerSellerProfilRouteImport.update({
  id: '/seller/profil',
  path: '/seller/profil',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSellerDashboardRoute = SellerSellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSellerProdukIndexRoute = SellerSellerProdukIndexRouteImport.update({
  id: '/seller/produk/',
  path: '/seller/produk/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSellerProdukTambahRoute =
  SellerSellerProdukTambahRouteImport.update({
    id: '/seller/produk/tambah',
    path: '/seller/produk/tambah',
    getParentRoute: () => SellerRoute,
  } as any)
const SellerSellerProdukProdukIdEditRoute =
  SellerSellerProdukProdukIdEditRouteImport.update({
    id: '/seller/produk/$produkId/edit',
    path: '/seller/produk/$produkId/edit',
    getParentRoute: () => SellerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tentang': typeof TentangRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/register': typeof SellerRegisterRoute
  '/toko/$sellerId': typeof TokoSellerIdRoute
  '/toko/$slugToko': typeof TokoSlugTokoRoute
  '/produk/': typeof ProdukIndexRoute
  '/seller/dashboard': typeof SellerSellerDashboardRoute
  '/seller/profil': typeof SellerSellerProfilRoute
  '/seller/produk/tambah': typeof SellerSellerProdukTambahRoute
  '/seller/produk/': typeof SellerSellerProdukIndexRoute
  '/seller/produk/$produkId/edit': typeof SellerSellerProdukProdukIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tentang': typeof TentangRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/register': typeof SellerRegisterRoute
  '/toko/$sellerId': typeof TokoSellerIdRoute
  '/toko/$slugToko': typeof TokoSlugTokoRoute
  '/produk': typeof ProdukIndexRoute
  '/seller/dashboard': typeof SellerSellerDashboardRoute
  '/seller/profil': typeof SellerSellerProfilRoute
  '/seller/produk/tambah': typeof SellerSellerProdukTambahRoute
  '/seller/produk': typeof SellerSellerProdukIndexRoute
  '/seller/produk/$produkId/edit': typeof SellerSellerProdukProdukIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_seller': typeof SellerRouteWithChildren
  '/tentang': typeof TentangRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/register': typeof SellerRegisterRoute
  '/toko/$sellerId': typeof TokoSellerIdRoute
  '/toko/$slugToko': typeof TokoSlugTokoRoute
  '/produk/': typeof ProdukIndexRoute
  '/_seller/seller/dashboard': typeof SellerSellerDashboardRoute
  '/_seller/seller/profil': typeof SellerSellerProfilRoute
  '/_seller/seller/produk/tambah': typeof SellerSellerProdukTambahRoute
  '/_seller/seller/produk/': typeof SellerSellerProdukIndexRoute
  '/_seller/seller/produk/$produkId/edit': typeof SellerSellerProdukProdukIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tentang'
    | '/produk/$slug'
    | '/seller/login'
    | '/seller/register'
    | '/toko/$sellerId'
    | '/toko/$slugToko'
    | '/produk/'
    | '/seller/dashboard'
    | '/seller/profil'
    | '/seller/produk/tambah'
    | '/seller/produk/'
    | '/seller/produk/$produkId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tentang'
    | '/produk/$slug'
    | '/seller/login'
    | '/seller/register'
    | '/toko/$sellerId'
    | '/toko/$slugToko'
    | '/produk'
    | '/seller/dashboard'
    | '/seller/profil'
    | '/seller/produk/tambah'
    | '/seller/produk'
    | '/seller/produk/$produkId/edit'
  id:
    | '__root__'
    | '/'
    | '/_seller'
    | '/tentang'
    | '/produk/$slug'
    | '/seller/login'
    | '/seller/register'
    | '/toko/$sellerId'
    | '/toko/$slugToko'
    | '/produk/'
    | '/_seller/seller/dashboard'
    | '/_seller/seller/profil'
    | '/_seller/seller/produk/tambah'
    | '/_seller/seller/produk/'
    | '/_seller/seller/produk/$produkId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SellerRoute: typeof SellerRouteWithChildren
  TentangRoute: typeof TentangRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  SellerLoginRoute: typeof SellerLoginRoute
  SellerRegisterRoute: typeof SellerRegisterRoute
  TokoSellerIdRoute: typeof TokoSellerIdRoute
  TokoSlugTokoRoute: typeof TokoSlugTokoRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_seller': {
      id: '/_seller'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toko/$slugToko': {
      id: '/toko/$slugToko'
      path: '/toko/$slugToko'
      fullPath: '/toko/$slugToko'
      preLoaderRoute: typeof TokoSlugTokoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toko/$sellerId': {
      id: '/toko/$sellerId'
      path: '/toko/$sellerId'
      fullPath: '/toko/$sellerId'
      preLoaderRoute: typeof TokoSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/register': {
      id: '/seller/register'
      path: '/seller/register'
      fullPath: '/seller/register'
      preLoaderRoute: typeof SellerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/login': {
      id: '/seller/login'
      path: '/seller/login'
      fullPath: '/seller/login'
      preLoaderRoute: typeof SellerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_seller/seller/profil': {
      id: '/_seller/seller/profil'
      path: '/seller/profil'
      fullPath: '/seller/profil'
      preLoaderRoute: typeof SellerSellerProfilRouteImport
      parentRoute: typeof SellerRoute
    }
    '/_seller/seller/dashboard': {
      id: '/_seller/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerSellerDashboardRouteImport
      parentRoute: typeof SellerRoute
    }
    '/_seller/seller/produk/': {
      id: '/_seller/seller/produk/'
      path: '/seller/produk'
      fullPath: '/seller/produk/'
      preLoaderRoute: typeof SellerSellerProdukIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/_seller/seller/produk/tambah': {
      id: '/_seller/seller/produk/tambah'
      path: '/seller/produk/tambah'
      fullPath: '/seller/produk/tambah'
      preLoaderRoute: typeof SellerSellerProdukTambahRouteImport
      parentRoute: typeof SellerRoute
    }
    '/_seller/seller/produk/$produkId/edit': {
      id: '/_seller/seller/produk/$produkId/edit'
      path: '/seller/produk/$produkId/edit'
      fullPath: '/seller/produk/$produkId/edit'
      preLoaderRoute: typeof SellerSellerProdukProdukIdEditRouteImport
      parentRoute: typeof SellerRoute
    }
  }
}

interface SellerRouteChildren {
  SellerSellerDashboardRoute: typeof SellerSellerDashboardRoute
  SellerSellerProfilRoute: typeof SellerSellerProfilRoute
  SellerSellerProdukTambahRoute: typeof SellerSellerProdukTambahRoute
  SellerSellerProdukIndexRoute: typeof SellerSellerProdukIndexRoute
  SellerSellerProdukProdukIdEditRoute: typeof SellerSellerProdukProdukIdEditRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerSellerDashboardRoute: SellerSellerDashboardRoute,
  SellerSellerProfilRoute: SellerSellerProfilRoute,
  SellerSellerProdukTambahRoute: SellerSellerProdukTambahRoute,
  SellerSellerProdukIndexRoute: SellerSellerProdukIndexRoute,
  SellerSellerProdukProdukIdEditRoute: SellerSellerProdukProdukIdEditRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SellerRoute: SellerRouteWithChildren,
  TentangRoute: TentangRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  SellerLoginRoute: SellerLoginRoute,
  SellerRegisterRoute: SellerRegisterRoute,
  TokoSellerIdRoute: TokoSellerIdRoute,
  TokoSlugTokoRoute: TokoSlugTokoRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
